apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-test
  labels:
    app: kustomize-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kustomize-test
  template:
    metadata:
      labels:
        app: kustomize-test
    spec:
      serviceAccountName: vault-auth
      volumes:
        - name: vault-token
          emptyDir:
            medium: Memory

        - name: config
          configMap:
            name: vault-agent-config
            items:
              - key: vault-agent-config.hcl
                path: vault-agent-config.hcl

              - key: consul-template-config.hcl
                path: consul-template-config.hcl

        - name: shared-data
          emptyDir: {}

        - name: vault-tls
          secret: 
            secretName: vault-tls

 #######################################################

      containers:
        # Vault Agent container
        # The vault-agent container authenticates the container using the
        # kubernetes auth method and puts the resulting token on the filesystem.
        - name: vault-agent-auth
          image: vault

          volumeMounts:
            - name: vault-token
              mountPath: /home/vault
            - name: config
              mountPath: /etc/vault
            - name: vault-tls
              mountPath: /etc/vault/tls
          
          env:
            - name: VAULT_ADDR
              value: https://35.188.166.188:443
            - name: VAULT_CACERT
              value: /etc/vault/tls/ca.crt
            - name: VAULT_ROLE
              value: agent-role

          # Run the Vault agent
          args:
            [
              "agent",
              "-config=/etc/vault/vault-agent-config.hcl",
              #"-log-level=debug",
            ]

    ########################################################

        # Consul Template container
        # The consul-template container will pull secrets from Vault and expose
        # them as files on disk.
        - name: consul-template
          image: hashicorp/consul-template
          imagePullPolicy: Always

          volumeMounts:
            - name: vault-token
              mountPath: /home/vault
            - name: config
              mountPath: /etc/consul-template
            - name: shared-data
              mountPath: /etc/secrets
            - name: vault-tls 
              mountPath: /etc/vault/tls
              
          env:
            - name: HOME
              value: /home/vault
            - name: VAULT_ADDR
              value: https://35.188.166.188:443
            - name: VAULT_CACERT
              value: /etc/vault/tls/ca.crt

          # Consul-Template looks in $HOME/.vault-token, $VAULT_TOKEN, or -vault-token (via CLI)
          args:
            [
              "-config=/etc/consul-template/consul-template-config.hcl",
              #"-log-level=debug",
            ]

    ####################################################################
        # Actual app container
        - name: kustomize-test
          image: nginx
          ports:
          - containerPort: 80

          volumeMounts:
          - name: shared-data
            mountPath: /usr/share/nginx/html
