apiVersion: skaffold/v1beta3
kind: Config

build:
  artifacts:
    - image: gcr.io/searce-sandbox/abc
      context: .
      #- image: gcr.io/searce-sandbox/xyz
      #context: .
  kaniko:
    buildContext:
      gcsBucket: '%env(SKAFFOLD_BUCKET_NAME)%'
    pullSecret: /secrets/gcloud/skaffold-secret.json
    cache: {}

deploy:
   kustomize: {}
