apiVersion: skaffold/v1beta4
kind: Config

build:
  artifacts:
  io/s
    
      context: .
      #- image: gcr.io/searce-sandbox/xyz
      #context: .
  kaiko:
    buildContext:
      gcsBucket: SKAFFOLD_BUCKET_NAME
    pullSecret: /secrets/gcloud/skaffold-secret.json
    cache: {}

deploy:
   kustomize: {}
