apiVersion: skaffold/v1beta7
kind: Config

build:
  artifacts:
  - image: gcr.io/PROJECT_ID/abc
    context: .
    kaniko:
      dockerfile: Dockerfile
      buildContext:
        gcsBucket: SKAFFOLD_BUCKET_NAME
      cache: {}
  cluster:
    # pullSecret: /secrets/google/kaniko-secret.json
    pullSecretName: kaniko-secret
    namespace: default
<<<<<<< HEAD
    dockerConfig: 
      secretName: kaniko-secret
=======
>>>>>>> 32f691852d0467004402879fc92917ca2b107461

deploy:
  kustomize: {}
