apiVersion: skaffold/v1beta4
kind: Config

build:
  artifacts:
    - image: gcr.io/searce-sandbox/abc
      context: .
      kaniko:
        buildContext:
          gcsBucket: SKAFFOLD_BUCKET_NAME
        cache: {}
  cluster:
    pullSecret: /secrets/gcloud/skaffold-secret.json

deploy:
   kustomize: {}
