apiVersion: skaffold/v1beta7
kind: Config

build:
  artifacts:
    - image: gcr.io/PROJECT_ID/abc
      context: .
      kaniko:
        buildContext:
          gcsBucket: SKAFFOLD_BUCKET_NAME
        cache: {}
  cluster:
    pullSecret: /secrets/google/kaniko-secret.json
    # pullSecretName: kaniko-secret

deploy:
  kustomize: {}
