apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
    - image: gcr.io/searce-sandbox/abc
      context: .
      #- image: gcr.io/searce-sandbox/xyz
      #context: .
  kaniko:
    buildContext:
    # localDir: {}
      gcsBucket: mukesh-test-bucket
    pullSecret: /secrets/gcloud/skaffold-secret.json
   # namespace: build-helloworld
    cache: {}

deploy:
   kustomize: {}
