apiVersion: skaffold/v1beta7
kind: Config

build:
  artifacts:
    - image: gcr.io/searce-sandbox/abc
      kaniko:
        buildContext:
          gcsBucket: SKAFFOLD_BUCKET_NAME
        pullSecret: /secrets/gcloud/skaffold-secret.json
        cache: {}

deploy:
   kustomize: {}
